### ISSUE TITLE
action编译出错

### ISSUE THREAD

**Issue by 0093Axis** [MeIsReallyBa/padavan-4.4#1]
action编译报错 `WARNING: 'aclocal-1.15' is missing on your system.`
根据之前keke1023库的经验应该是本机编译遗留的文件导致的 清理下编译产生的文件再push下吧

**Comment by MeIsReallyBa** [comment]
好像是这样。。。我clear_tree了再传的，不知道还有啥文件没删掉。。。

**Comment by 0093Axis** [comment]
可以看下我的commit 都是已解压的tarball文件夹 不过我不确定删完了
另外我这边测试JCG-Y2有线不识别 不能获得DHCP地址 PC强制指定也不能连接 蒙逼···

**Comment by MeIsReallyBa** [comment]
删除后试了在线编译能过了。
