### ISSUE TITLE
红米2100 2.4G KVR 无法开启

### ISSUE THREAD

**Issue by yaotthaha** [MeIsReallyBa/padavan-4.4#102]
wifi监测：

![image](https://user-images.githubusercontent.com/95022881/210086492-c1e535b4-4e08-4555-8344-189f2b04cfb8.png)

padavan配置：

![image](https://user-images.githubusercontent.com/95022881/210086581-87f6959c-a173-425c-b0cd-290fa0b659df.png)

**Comment by AdamTyn** [comment]
这个路由器本来就不支持kvr啊

**Comment by yaotthaha** [comment]
那看来只能用openwrt开源驱动了
