### ISSUE TITLE
Newifi3无法拨号固定IP也有问题无法上网

### ISSUE THREAD

**Issue by MxCen** [MeIsReallyBa/padavan-4.4#103]
Newifi3无法拨号，静态IP也有问题，正确配置后，无法上网

**Comment by ghwrf** [comment]
NEWIFI3(from https://github.com/GH-X/padavan-4.4, 必须拆除主板上编号为C48的电容(位于CPU旁边), 否则外网(WAN)将不能正常工作)

**Comment by ghwrf** [comment]
我没有拆，目前还没搞定。
