### ISSUE TITLE
MT76x2E驱动5G网络很卡很慢，2.4G出乎意料不错

### ISSUE THREAD

**Issue by simonchen** [MeIsReallyBa/padavan-4.4#107]
环境：5G作AP+Client 或者 2.4G作AP+Client
5G下行速度不正常，非常卡，同等环境下2.4G飞快

希望能解决此问题 ，3.4内核不存在此问题

**Comment by simonchen** [comment]
> 环境：5G作AP+Client 或者 2.4G作AP+Client 5G下行速度不正常，非常卡，同等环境下2.4G飞快
> 
> 希望能解决此问题 ，3.4内核不存在此问题

和前面的有个帖出的问题是一样的，单线程 iperf3下载速度只有1Mbps/s，在多线程下正常，严重怀疑是MT76x2驱动和新内核不兼容问题麻烦大佬看看！

**Comment by DoveKi** [comment]
@MeIsReallyBa [https://github.com/MeIsReallyBa/padavan-4.4/issues/67](url)

**Comment by simonchen** [comment]
> @MeIsReallyBa [issues67](https://github.com/MeIsReallyBa/padavan-4.4/issues/67)

github 云编译用ubuntu-22.04 可能有点问题，
试了在本地vmware下ubuntu-20.04编译出来的固件，mt76x2的5G单线程下行似乎是正常的。

**Comment by MeIsReallyBa** [comment]
7612我没机器，云适配的。问题应该在硬件加速上，因为7603 7615 7915默认支持4.4的硬件加速，7612我手动改的，也没机器测试。

**Comment by simonchen** [comment]
> 7612我没机器，云适配的。问题应该在硬件加速上，因为7603 7615 7915默认支持4.4的硬件加速，7612默认不支持，我手动改的，也没机器测试。

有没有办法调整CONFIG在编译时让MT76x2_ap去掉HWNAT加速？然后，我再测试一下. 

另外，你可以花50元买个newifi-d1，测试一下，谢谢*_*

**Comment by MeIsReallyBa** [comment]
no plan

**Comment by MeIsReallyBa** [comment]
no plan

**Comment by simonchen** [comment]
> no plan。自行修复，

thanks man, I'm really appreciated for your help.
in addition, I've checked through some codes, the HW NAT would be related to the 'Reath' module , maybe that need to roll out the module also. I'm not sure where did you get the MTK driver for MT76x3, why there is no new driver to adapt for MT76x2 for Linux kernel 4.4.x?

**Comment by MeIsReallyBa** [comment]
换了新的hnat，不需要无线驱动适配，应该能解决了。

**Comment by simonchen** [comment]
> 换了新的hnat，不需要无线驱动适配，应该能解决了。

非常感谢！

**Comment by simonchen** [comment]
> 换了新的hnat，不需要无线驱动适配，应该能解决了。

非常感谢，替换了更新的ra_nat.c ，重新编译后，问题依旧存在 。。。
另外，会不会是mt76x2的驱动中和Kthread有关的代码造成的?

**Comment by simonchen** [comment]
> 换了新的hnat，不需要无线驱动适配，应该能解决了。

重新编译了(NEWIFI配置)，在newifi-d1上还是一样， 单线程下行只有1~2Mbps/s

**Comment by MeIsReallyBa** [comment]
那无线驱动本身的问题，自己修吧。2023了我不可能还去买7612这十年前的东西
